// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njsfsbyvgkeawmxgjivw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qc2ZzYnl2Z2tlYXdteGdqaXZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2OTAzNzgsImV4cCI6MjA3NDI2NjM3OH0.n3YtzUkthr4eHT3xfUDHzxKvQHL7D0VceRKF7dzBYLs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});